### ISSUE TITLE
Connect the Graduate Student Checklist

### ISSUE THREAD

**Issue by franceme** [CSGraduateCouncil-VirginiaTech/csgc-website#97]
Connect the Graduate Student Checklist from [Link](https://paper.dropbox.com/doc/Grad-Student-Checklist-tVJpwHfjJMe5t5A7KN5Uh)

**Comment by franceme** [comment]
*  Dynamically or statically load the Graduate Student Checklist
    * dynamically i.e. it seems to sync on Google Drive, maybe we could just load and render from the URL to keep using Dropbox Paper?
* Put a In Progress or Solely a Guideline clarification

**Comment by ShGoldfish** [comment]
@ffrankies The version on Drive ([here](https://drive.google.com/drive/u/0/folders/1YLHiSvDtYLx_QM3bYAjdnAimcooy0Qgd)) is up-to-date. we just want to add a "Graduate Student Checklist" to the side-bar linking to a new page that dynamically has the content of the pdf embedded in it. [I think you can just include the html for embedding pdf image]
